// urbanrail.net 連結映射（物件 tab Info 區用）——純資料，與 UI 無耦合。
// urbanrail.net：城市頁 URL 不規則（城市碼縮寫沒有算法規律，台北 tw/taip/taipei.htm、
// 新加坡 sing/singapore.htm、蒙特雷 mony/monterrey.htm），故用實查的城市→URL 映射
// （key = index.json 的 city）。映射是把 urbanrail 五大洲索引頁（as/asia.htm 等）的
// 圖像地圖 area + 文字錨點全部解析出來、再和本專案 224 城比對而成（scripts 見
// scratchpad/match.mjs），223 城全部命中並 curl 驗證 HTTP 200。少數郊區城市指向其
// 所屬系統的母頁（Xirivella→西班牙 Valencia、Noida/Gurgaon→Delhi、Gimpo→Seoul、
// Ratingen→Düsseldorf）。唯一沒有 urbanrail 專頁的 Bezirk Landeck（奧地利）fallback
// 到洲索引頁。URL = 洲碼前綴 + 洲索引頁裡的相對 href（href 相對於洲目錄）。
export const URBANRAIL_CITIES = {
  "Adana": "as/tr/adana/adana.htm",
  "Agra": "as/in/agra/agra.htm",
  "Ahmedabad": "as/in/ahmedabad/ahmedabad.htm",
  "Algiers": "af/alg/algiers.htm",
  "Almaty": "as/kz/almaty/almaty.htm",
  "Amsterdam": "eu/nl/ams/amsterdam.htm",
  "Ankara": "as/tr/ankara/ankara.htm",
  "Astana": "as/kz/astana/astana.htm",
  "Athens": "eu/gr/athens/athens.htm",
  "Atlanta": "am/atla/atlanta.htm",
  "Baku": "as/baku/baku.htm",
  "Baltimore": "am/balt/baltimore.htm",
  "Bangkok": "as/bang/bangkok.htm",
  "Barcelona": "eu/es/bcn/barcelona.htm",
  "Beijing": "as/cn/beij/beijing.htm",
  "Belo Horizonte": "am/belo/belo-horizonte.htm",
  "Bengaluru": "as/in/banl/bangalore.htm",
  "Berlin": "eu/de/b/berlin.htm",
  "Bhopal": "as/in/bhopal/bhopal.htm",
  "Bielefeld": "eu/de/bi/bielefeld.htm",
  "Bilbao": "eu/es/bilbao/bilbao.htm",
  "Bochum": "eu/de/bo/bochum.htm",
  "Boston": "am/bost/boston.htm",
  "Brasília": "am/bras/brasilia.htm",
  "Brescia": "eu/it/bre/brescia.htm",
  "Brussels": "eu/be/brux/brussels.htm",
  "Bucharest": "eu/ro/buc/bucurest.htm",
  "Budapest": "eu/hu/budapest/budapest.htm",
  "Buenos Aires": "am/buen/buenos-aires.htm",
  "Bursa": "as/tr/bursa/bursa.htm",
  "Busan": "as/kr/busan/busan.htm",
  "Cairo": "af/cairo/cairo.htm",
  "Caracas": "am/cara/caracas.htm",
  "Catania": "eu/it/cat/catania.htm",
  "Changchun": "as/cn/chan/changchun.htm",
  "Changsha": "as/cn/changsha/changsha.htm",
  "Changzhou": "as/cn/changzhou/changzhou.htm",
  "Chengdu": "as/cn/chdu/chengdu.htm",
  "Chennai": "as/in/chen/chennai.htm",
  "Chiba Prefecture": "as/jp/chiba/chiba.htm",
  "Chicago": "am/chic/chicago.htm",
  "Chongqing": "as/cn/chon/chongqing.htm",
  "Chuzhou": "as/cn/nanj/nanjing.htm",
  "Cleveland": "am/clev/cleveland.htm",
  "Copenhagen": "eu/dk/kobenhavn/kobenhavn.htm",
  "Daegu": "as/kr/daegu/daegu.htm",
  "Daejeon": "as/kr/daejeon/daejeon.htm",
  "Dalian": "as/cn/dalian/dalian.htm",
  "Delhi": "as/in/delhi/delhi.htm",
  "Derince": "as/tr/izmit/izmit.htm",
  "Dhaka": "as/dhaka/dhaka.htm",
  "Dnipro": "eu/ua/dnipro/dnipro.htm",
  "Doha": "as/doha/doha.htm",
  "Dongguan": "as/cn/dongguan/dongguan.htm",
  "Dubai": "as/dub/dubai.htm",
  "Dusseldorf": "eu/de/d/duesseldorf.htm",
  "Essen": "eu/de/e/essen.htm",
  "Fortaleza": "am/fort/fortaleza.htm",
  "Foshan": "as/cn/guan/foshan.htm",
  "Frankfurt": "eu/de/f/frankfurt.htm",
  "Fukuoka": "as/jp/fukuoka/fukuoka.htm",
  "Fuzhou": "as/cn/fuzhou/fuzhou.htm",
  "Genoa": "eu/it/gen/genova.htm",
  "Gimpo": "as/kr/seoul/seoul.htm",
  "Glasgow": "eu/uk/gla/glasgow.htm",
  "Guadalajara": "am/guad/guadalajara.htm",
  "Guangzhou": "as/cn/guan/guangzhou.htm",
  "Guiyang": "as/cn/guiyang/guiyang.htm",
  "Gurgaon": "as/in/delhi/delhi.htm",
  "Gwangju": "as/kr/gwangju/gwangju.htm",
  "Hamburg": "eu/de/hh/hamburg.htm",
  "Hangzhou": "as/cn/hang/hangzhou.htm",
  "Hanoi": "as/hanoi/hanoi.htm",
  "Harbin": "as/cn/harbin/harbin.htm",
  "Hefei": "as/cn/hefei/hefei.htm",
  "Helsinki": "eu/fi/helsinki//helsinki.htm",
  "Hiroshima": "as/jp/hiroshima/hiroshima.htm",
  "Ho Chi Minh City": "as/hcmc/ho-chi-minh-city.htm",
  "Hohhot": "as/cn/hohhot/hohhot.htm",
  "Hong Kong": "as/cn/hong/hong-kong.htm",
  "Honolulu": "am/hono/honolulu.htm",
  "Hyderabad": "as/in/hydr/hyderabad.htm",
  "Incheon": "as/kr/incheon/incheon.htm",
  "Indore": "as/in/indore/indore.htm",
  "Isfahan": "as/ir/isfa/isfahan.htm",
  "Istanbul": "as/tr/istanbul/istanbul.htm",
  "İzmir": "as/tr/izmir/izmir.htm",
  "Jaipur": "as/in/jaip/jaipur.htm",
  "Jakarta": "as/id/jaka/jakarta.htm",
  "Jinan": "as/cn/jinan/jinan.htm",
  "Jinhua": "as/cn/jinhua/jinhua.htm",
  "Kanpur": "as/in/kanpur/kanpur.htm",
  "Kaohsiung": "as/tw/kaoh/kaohsiung.htm",
  "Karaj": "as/ir/karaj/karaj.htm",
  "Kazan": "eu/ru/kaz/kazan.htm",
  "Kharkiv": "eu/ua/kha/kharkiv.htm",
  "Kobe": "as/jp/kobe/kobe.htm",
  "Kochi": "as/in/kochi/kochi.htm",
  "Kolkata": "as/in/kolk/kolkata.htm",
  "Kuala Lumpur": "as/my/kual/kuala-lumpur.htm",
  "Kunming": "as/cn/kunming/kunming.htm",
  "Kyiv": "eu/ua/kiev/kyiv.htm",
  "Kyoto": "as/jp/kyoto/kyoto.htm",
  "Lagos": "af/lagos/lagos.htm",
  "Lahore": "as/lahore/lahore.htm",
  "Lanzhou": "as/cn/lanzhou/lanzhou.htm",
  "Lausanne": "eu/ch/vd/lausanne.htm",
  "Lille": "eu/fr/lille/lille.htm",
  "Lima": "am/lima/lima.htm",
  "Lisbon": "eu/pt/lisboa/lisboa.htm",
  "London": "eu/uk/lon/london.htm",
  "Los Angeles": "am/lsan/los-angeles.htm",
  "Lucknow": "as/in/lucknow/lucknow.htm",
  "Luoyang": "as/cn/luoyang/luoyang.htm",
  "Lyon": "eu/fr/lyon/lyon.htm",
  "Macau": "as/cn/macau/macau.htm",
  "Madrid": "eu/es/mad/madrid.htm",
  "Manila": "as/manila/manila.htm",
  "Maracaibo": "am/mara/maracaibo.htm",
  "Marseille": "eu/fr/marseille/marseille.htm",
  "Mashhad": "as/ir/mash/mashhad.htm",
  "Mecca": "as/mecca/makkah.htm",
  "Medellín": "am/mede/medellin.htm",
  "Meerut": "as/in/delhi/meerut-metro.htm",
  "Mexico City": "am/mexi/mexico.htm",
  "Miami": "am/miam/miami.htm",
  "Milan": "eu/it/mil/milano.htm",
  "Minsk": "eu/by/minsk/minsk.htm",
  "Monterrey": "am/mony/monterrey.htm",
  "Montreal": "am/monr/montreal.htm",
  "Moscow": "eu/ru/mos/moskva.htm",
  "Mumbai": "as/in/mumb/mumbai.htm",
  "Munich": "eu/de/m/muenchen.htm",
  "Nagoya": "as/jp/nagoya/nagoya.htm",
  "Nagpur": "as/in/nagpur/nagpur.htm",
  "Nanchang": "as/cn/nanchang/nanchang.htm",
  "Nanjing": "as/cn/nanj/nanjing.htm",
  "Nanning": "as/cn/nanning/nanning.htm",
  "Nantong": "as/cn/nantong/nantong.htm",
  "Naples": "eu/it/nap/napoli.htm",
  "Navi Mumbai": "as/in/mumb/navi-mumbai.htm",
  "New York City": "am/nyrk/new-york.htm",
  "Ningbo": "as/cn/ningbo/ningbo.htm",
  "Nizhny Novgorod": "eu/ru/niz/nizhniy-novgorod.htm",
  "Noida": "as/in/delhi/delhi.htm",
  "Novosibirsk": "eu/ru/novosib/novosibirsk-tram.htm",
  "Nuremberg": "eu/de/n/nuernberg.htm",
  "Osaka": "as/jp/osaka/osaka.htm",
  "Oslo": "eu/no/oslo/oslo.htm",
  "Palembang": "as/id/palem/palembang.htm",
  "Panama City": "am/pana/panama.htm",
  "Paris": "eu/fr/paris/paris.htm",
  "Patna": "as/in/patna/patna.htm",
  "Philadelphia": "am/phil/philadelphia.htm",
  "Porto Alegre": "am/ptal/porto-alegre.htm",
  "Prague": "eu/cz/praha/praha.htm",
  "Pune": "as/in/pune/pune.htm",
  "Pyongyang": "as/kr/pyongyang/pyongyang.htm",
  "Qingdao": "as/cn/qing/qingdao.htm",
  "Quito": "am/quito/quito.htm",
  "Ratingen": "eu/de/d/duesseldorf.htm",
  "Recife": "am/reci/recife.htm",
  "Rennes": "eu/fr/rennes/rennes.htm",
  "Rio de Janeiro": "am/rioj/rio-de-janeiro.htm",
  "Riyadh": "as/riyadh/riyadh.htm",
  "Rome": "eu/it/rom/roma.htm",
  "Rotterdam": "eu/nl/rot/rotterdam.htm",
  "Saint Petersburg": "eu/ru/pet/petersburg.htm",
  "Saitama Prefecture": "as/jp/tokyo/tokyo.htm",
  "Salvador": "am/salv/salvador.htm",
  "Samara": "eu/ru/sam/samara.htm",
  "San Francisco (Bay Area)": "am/snfr/sf-bay-area-map.htm",
  "San Juan": "am/snju/san-juan.htm",
  "Santiago": "am/sant/santiago.htm",
  "Santo Domingo": "am/sdom/santo-domingo.htm",
  "São Paulo": "am/spau/sao-paulo.htm",
  "Sapporo": "as/jp/sapporo/sapporo.htm",
  "Sendai": "as/jp/sendai/sendai.htm",
  "Seoul": "as/kr/seoul/seoul.htm",
  "Seville": "eu/es/sevilla/sevilla.htm",
  "Shanghai": "as/cn/shan/shanghai.htm",
  "Shaoxing": "as/cn/shaoxing/shaoxing.htm",
  "Shenyang": "as/cn/shny/shenyang.htm",
  "Shenzhen": "as/cn/shen/shenzhen.htm",
  "Shijiazhuang": "as/cn/shijiazhuang/shijiazhuang.htm",
  "Shiraz": "as/ir/shir/shiraz.htm",
  "Singapore": "as/sing/singapore.htm",
  "Sofia": "eu/bg/sofia/sofia.htm",
  "Stockholm": "eu/se/stockholm/stockhlm.htm",
  "Suzhou": "as/cn/suzh/suzhou.htm",
  "Sydney": "au/sydney/sydney.htm",
  "Tabriz": "as/ir/tabr/tabriz.htm",
  "Taichung": "as/tw/taichung/taichung.htm",
  "Taipei": "as/tw/taip/taipei.htm",
  "Taiyuan": "as/cn/taiyuan/taiyuan.htm",
  "Taizhou": "as/cn/taizhou/taizhou.htm",
  "Tashkent": "as/uz/toshkent/toshkent.htm",
  "Tbilisi": "as/tbil/tbilisi.htm",
  "Tehran": "as/ir/tehr/tehran.htm",
  "Thessaloniki": "eu/gr/thessaloniki/thessaloniki.htm",
  "Tianjin": "as/cn/tian/tianjin.htm",
  "Tokyo": "as/jp/tokyo/tokyo.htm",
  "Toronto": "am/toro/toronto.htm",
  "Toulouse": "eu/fr/toulouse/toulouse.htm",
  "Turin": "eu/it/tor/torino.htm",
  "Ürümqi": "as/cn/urumqi/urumqi.htm",
  "Valencia": "am/vale/valencia.htm",
  "Vancouver": "am/vanc/vancouver.htm",
  "Vienna": "eu/at/vienna/wien.htm",
  "Warsaw": "eu/pl/war/warszawa.htm",
  "Washington, D.C.": "am/wash/washington.htm",
  "Wenzhou": "as/cn/wenzhou/wenzhou.htm",
  "Wuhan": "as/cn/wuhan/wuhan.htm",
  "Wuhu": "as/cn/wuhu/wuhu.htm",
  "Wuxi": "as/cn/wuxi/wuxi.htm",
  "Xi'an": "as/cn/xian/xian.htm",
  "Xiamen": "as/cn/xiamen/xiamen.htm",
  "Xirivella": "eu/es/val/valencia.htm",
  "Xuzhou": "as/cn/xuzhou/xuzhou.htm",
  "Yekaterinburg": "eu/ru/yekatarin/yekaterinburg-tram.htm",
  "Yerevan": "as/yere/yerevan.htm",
  "Yokohama": "as/jp/yokohama/yokohama.htm",
  "Zhengzhou": "as/cn/zheng/zhengzhou.htm",
}
export const URBANRAIL_CONTINENTS = {
  asia: 'as/asia.htm',
  europe: 'eu/euromet.htm',
  'north-america': 'am/america.htm',
  'south-america': 'am/america.htm',
  africa: 'af/africa.htm',
  oceania: 'au/oceania.htm',
}
